### ISSUE TITLE
DNS resolver is not working when Docker is run with colima

### ISSUE THREAD

**Issue by Flower7C3** [docksal/docksal#1630]
**Description**

DNS resolver is not working when Docker is run with colima

**Steps to reproduce the issue:**

> Before testing check Docker context (so You will be able to rollback configuration) with `docker context show` command.

1. Stop Docker Desktop
2. Install [colima](https://github.com/abiosoft/colima)
3. Start colima `colima start`
4. Restart Docksal `fin system reset`
5. Check sysinfo with `fin sysinfo`

> If You want to rollback configuration just remove colima and switch back to previous Docker context with `docker context use NAME`, where name was printed before testing.

**Describe the results you received:**

```
Checking connectivity to http://dns-test.docksal...
Host: FAIL
```

**Describe the results you expected:**

```
Checking connectivity to http://dns-test.docksal...
Host: PASS
```

**Output of `fin sysinfo`:**

<details>
  <summary>fin sysinfo output on colima</summary>

  ```
███  FIN
fin version: 1.107.1

███  OS
Darwin macOS 12.2.1
Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop
DOCKER_HOST : 

███  NFS
DOCKSAL_NFS_PATH : /Users

nfsd service is enabled
nfsd is running (pid 22495, 8 threads)

NFS EXPORTS
----------

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.1 -alldirs -maproot=0:0
# ds-nfs>
----------

Exports list on localhost:
/Users                              127.0.0.1 192.168.64.1

███  DOCKER
EXPECTED CLIENT VERSION: 20.10.7
EXPECTED SERVER VERSION: 20.10.7

Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           colima
 Experimental:      true

Server:
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.10
  Git commit:       847da184ad5048b27f5bdf9d53d070f731b43180
  Built:            Fri Nov 19 03:41:34 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.8
  GitCommit:        1e5ef943eb76627a6d3b6de8cd1ef6537f393a71
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        

███  DOCKER COMPOSE
EXPECTED VERSION: 1.29.2
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020

███  DOCKSAL: PROJECTS
project              STATUS                 virtual host                                                                           project root

███  DOCKSAL: VIRTUAL HOSTS

███  DOCKSAL: NETWORKING

DOCKSAL_IP: 192.168.64.100
DOCKSAL_HOST_IP: 192.168.64.1
DOCKSAL_VHOST_PROXY_IP: 0.0.0.0
DOCKSAL_DNS_IP: 0.0.0.0
DOCKSAL_DNS_DISABLED: 0
DOCKSAL_NO_DNS_RESOLVER: 0
DOCKSAL_DNS_UPSTREAM: 8.8.8.8
DOCKSAL_DNS_DOMAIN: docksal

███  DOCKSAL: CONNECTIVITY

Host to 192.168.64.100: 	PASS
Container to 192.168.64.100: 	PASS
Container to 192.168.64.1: 	PASS

Checking connectivity to http://dns-test.docksal...
Host: FAIL

Debug info:
----------
+ cat /etc/resolv.conf
+ grep 192.168.64.100
+ ping -c 1 -W 1 dns-test.docksal
ping: cannot resolve dns-test.docksal: Unknown host
+ nslookup -timeout=1 dns-test.docksal 192.168.64.100
;; connection timed out; no servers could be reached

+ set +x
----------

Containers: FAIL

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID   IMAGE                     COMMAND                  CREATED              STATUS                        PORTS                                                    NAMES
fcab964149d1   docksal/dns:1.1           "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:53->53/udp                                       docksal-dns
2eba93dedea9   docksal/ssh-agent:1.3     "docker-entrypoint.s…"   10 minutes ago       Up 10 minutes (healthy)                                                                docksal-ssh-agent
b23892c438bb   docksal/vhost-proxy:1.7   "docker-entrypoint.s…"   10 minutes ago       Up 10 minutes (healthy)       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                 docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID     NAME                         DRIVER    SCOPE
60ee1a400543   _default                     bridge    local
ea25d71c3a1b   bridge                       bridge    local
c96148142a77   host                         host      local
6419bc0e3ad9   none                         null      local

███  DOCKER DESKTOP
EXPECTED VERSION: 3.4.0
DETECTED VERSION: 4.5.0

███  HDD Usage
Filesystem                               Size   Used  Avail Capacity iused     ifree %iused  Mounted on
/dev/disk1s6s1                          466Gi   15Gi   29Gi    34%  577694 307473000    0%   /
devfs                                   193Ki  193Ki    0Bi   100%     669         0  100%   /dev
/dev/disk1s5                            466Gi   24Ki   29Gi     1%       0 307473000    0%   /System/Volumes/VM
/dev/disk1s3                            466Gi  471Mi   29Gi     2%    3055 307473000    0%   /System/Volumes/Preboot
/dev/disk1s7                            466Gi  4.8Mi   29Gi     1%      19 307473000    0%   /System/Volumes/Update
/dev/disk1s1                            466Gi  420Gi   29Gi    94% 3102148 307473000    1%   /System/Volumes/Data
/dev/disk1s2                            466Gi  780Ki   29Gi     1%      80 307473000    0%   /Volumes/Macintosh HD - Data
map auto_home                             0Bi    0Bi    0Bi   100%       0         0  100%   /System/Volumes/Data/home
map -fstab                                0Bi    0Bi    0Bi   100%       0         0  100%   /System/Volumes/Data/Network/Servers
  ```

</details>

<details>
  <summary>fin sysinfo output on Docker Desktop</summary>

  ```
███  FIN
fin version: 1.107.1

███  OS
Darwin macOS 12.2.1
Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

███  ENVIRONMENT
MODE : Docker Desktop
DOCKER_HOST : 

███  NFS
DOCKSAL_NFS_PATH : /Users

nfsd service is enabled
nfsd is running (pid 22495, 8 threads)

NFS EXPORTS
----------

# <ds-nfs docksal
/Users 127.0.0.1 192.168.64.1 -alldirs -maproot=0:0
# ds-nfs>
----------

Exports list on localhost:
/Users                              127.0.0.1 192.168.64.1

███  DOCKER
EXPECTED CLIENT VERSION: 20.10.7
EXPECTED SERVER VERSION: 20.10.7

Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.5.0 (74594)
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

███  DOCKER COMPOSE
EXPECTED VERSION: 1.29.2
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020

███  DOCKSAL: PROJECTS
project              STATUS                    virtual host                                                                           project root

███  DOCKSAL: VIRTUAL HOSTS

███  DOCKSAL: NETWORKING

DOCKSAL_IP: 192.168.64.100
DOCKSAL_HOST_IP: 192.168.64.1
DOCKSAL_VHOST_PROXY_IP: 0.0.0.0
DOCKSAL_DNS_IP: 0.0.0.0
DOCKSAL_DNS_DISABLED: 0
DOCKSAL_NO_DNS_RESOLVER: 0
DOCKSAL_DNS_UPSTREAM: 8.8.8.8
DOCKSAL_DNS_DOMAIN: docksal

███  DOCKSAL: CONNECTIVITY

Host to 192.168.64.100: 	PASS
Container to 192.168.64.100: 	PASS
Container to 192.168.64.1: 	PASS

Checking connectivity to http://dns-test.docksal...
Host: PASS
Containers: PASS

███  DOCKER: RUNNING CONTAINERS
CONTAINER ID   IMAGE                     COMMAND                  CREATED      STATUS                   PORTS                                      NAMES
d91b32d8d48e   docksal/ssh-agent:1.3     "docker-entrypoint.s…"   2 days ago   Up 5 minutes (healthy)                                              docksal-ssh-agent
6907aeba2349   docksal/dns:1.1           "docker-entrypoint.s…"   2 days ago   Up 5 minutes (healthy)   0.0.0.0:53->53/udp                         docksal-dns
e7267c02873e   docksal/vhost-proxy:1.7   "docker-entrypoint.s…"   2 days ago   Up 5 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docksal-vhost-proxy

███  DOCKER: NETWORKS
NETWORK ID     NAME       DRIVER    SCOPE
7b2b4277c904   _default   bridge    local
9b6588997c93   bridge     bridge    local
24c9dd815d57   host       host      local
520d0f01aa7b   none       null      local

███  DOCKER DESKTOP
EXPECTED VERSION: 3.4.0
DETECTED VERSION: 4.5.0

███  HDD Usage
Filesystem                               Size   Used  Avail Capacity iused     ifree %iused  Mounted on
/dev/disk1s6s1                          466Gi   15Gi   29Gi    34%  577694 307232640    0%   /
devfs                                   193Ki  193Ki    0Bi   100%     669         0  100%   /dev
/dev/disk1s5                            466Gi   24Ki   29Gi     1%       0 307232640    0%   /System/Volumes/VM
/dev/disk1s3                            466Gi  471Mi   29Gi     2%    3055 307232640    0%   /System/Volumes/Preboot
/dev/disk1s7                            466Gi  4.8Mi   29Gi     1%      19 307232640    0%   /System/Volumes/Update
/dev/disk1s1                            466Gi  420Gi   29Gi    94% 3102280 307232640    1%   /System/Volumes/Data
/dev/disk1s2                            466Gi  780Ki   29Gi     1%      80 307232640    0%   /Volumes/Macintosh HD - Data
map auto_home                             0Bi    0Bi    0Bi   100%       0         0  100%   /System/Volumes/Data/home
map -fstab                                0Bi    0Bi    0Bi   100%       0         0  100%   /System/Volumes/Data/Network/Servers
  ```

</details>

**Comment by lmakarov** [comment]
See my suggestion over here https://github.com/docksal/docksal/issues/1617#issuecomment-1047269898. Should solve this.

**Comment by Flower7C3** [comment]
@lmakarov thanks. Site is working when I switch to *.docksal.site.

But I still do not know why local DNS resolver is is not working over colima. When I run `scutil --dns` there is value:
```
resolver #8
  domain   : docksal
  nameserver[0] : 192.168.64.100
  flags    : Request A records
  reach    : 0x00000002 (Reachable)
```

**Comment by lmakarov** [comment]
What do you get from these?

```
nslookup test.docksal 192.168.64.100
nslookup test.docksal
```

**Comment by Flower7C3** [comment]
- nslookup test.docksal 192.168.64.100
```
;; connection timed out; no servers could be reached
```

- nslookup test.docksal

```
Server:		10.0.12.1
Address:	10.0.12.1#53

** server can't find test.docksal: NXDOMAIN
```

**Comment by lmakarov** [comment]
ok, I see what's going on. You would need to assign `192.168.63.100` (Docksal's canonical IP) to colima/lima VM.
Should be covered in docs here: https://github.com/lima-vm/lima/blob/master/docs/network.md

That said. I would just disable Docksal DNS and use the publicly resolvable `.docksal.site` domain. We plan on moving to that anyway at some point.

**Comment by lmakarov** [comment]
I will move this to Discussion as it is an off-topic for the Docksal issue queue.
