### ISSUE TITLE
Running `fin up` ignores DOCKSAL_VOLUMES in global configuration

### ISSUE THREAD

**Issue by GMTA** [docksal/docksal#712]
**Description**
Setting `DOCKSAL_VOLUMES` in `~/.docksal/docksal.env` works for most commands such as `fin reset` but not `fin up` because that explicitly "reloads the configuration" and sets `DOCKSAL_VOLUMES` to an empty string.

The use case is that for development machine configuration, I would like the default to be `nfs` mounts instead of `bind` mounts. On a per-project basis this can then be overriden in the project-specific `docksal.env`. Without global configuration support, we need to set `DOCKSAL_VOLUMES` explicitly for each project.

**Steps to reproduce the issue:**

1. Run `fin config set --global DOCKSAL_VOLUMES=nfs`
2. Go to a project without `DOCKSAL_VOLUMES` set in its `docksal.env` file
3. Run `fin up`

**Describe the results you received:**
A `bind` volume is created.

**Describe the results you expected:**
A `nfs` volume is created.

**Suggested fix**
Do not empty `DOCKSAL_VOLUMES` on `fin up`, just like it works on a `fin reset`.

**Comment by achekulaev** [comment]
I am not sure why you created duplicate of https://github.com/docksal/docksal/issues/709

**Comment by achekulaev** [comment]
I cannot replicate it on the develop version of the `fin` so I assume it was fixed at some point. Maybe inadvertently.

```
21:43:22 ~/Projects/test
§ fin config set --global DOCKSAL_VOLUMES=nfs
Added value for DOCKSAL_VOLUMES into /Users/oleksii_chekulaiev/.docksal/docksal.env

21:43:33 ~/Projects/test
§ fin config
...
volumes:
  docksal_ssh_agent:
    external: true
    name: docksal_ssh_agent
  project_root:
    driver: local
    driver_opts:
      device: :/Users/oleksii_chekulaiev/Projects/test
      o: addr=192.168.64.1,vers=3,nolock,noacl,nocto,noatime,nodiratime,tcp,actimeo=1
      type: nfs
```

**Comment by GMTA** [comment]
@achekulaev I just tested with the `develop` branch and it is still broken.

You should run `fin up`, not `fin config`. The problem is that `fin up` applies a _different_ config than what `fin config` will show you, which is a nasty bug on its own :-)
