### ISSUE TITLE
fin db commands don't work in non-interactive environments

### ISSUE THREAD

**Issue by lmakarov** [docksal/docksal#785]
When used in non-interactive (CI) environments, `fin db` commands fail with the error `the input device is not a TTY`.

Here's the way this can be reproduced locally:

```
$ echo 'fin db create test' | bash
the input device is not a TTY
 ERROR:  Database 'test' creation failed
```

```
$ echo 'fin db drop test' | bash
the input device is not a TTY
 ERROR:  Dropping 'test' database failed
```

```
$ echo 'fin db cli "GRANT ALL PRIVILEGES ON test.* TO user;"' | bash
the input device is not a TTY
```

As a temporary workaround, the following approach can be used:

`fin db create test` =>

```
fin docker-compose exec -T db mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
fin docker-compose exec -T db mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON test.* TO user;"
```

**Comment by achekulaev** [comment]
This is what I get running right now

```
§ echo 'fin db create test' | bash
 ALERT:  Required Docker version is 18.09.3
         Run fin update to update to the required version.
          
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Database test created
```

**Comment by achekulaev** [comment]
I fixed in in scope of https://github.com/docksal/docksal/issues/947 with https://github.com/docksal/docksal/commit/3e476dc742fc72bbc20d87e1302da1c2aa650049

**Comment by halisonfernandes** [comment]
Hello,

In the latest docksal version (1.99.0) this issue still happen.

**Comment by lmakarov** [comment]
> In the latest docksal version (1.99.0) this issue still happen.

I can confirm that:

```
$ echo 'fin db create test' | bash
the input device is not a TTY
 ERROR:  Database 'test' creation failed
```

cc @achekulaev

**Comment by lmakarov** [comment]
Actually, this ticket was closed as a duplicate. I'm going to reopen the other one - #947
